name: restrict_main_pr
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo branches
      run: echo "PR request from ${{ github.base_ref }} to ${{ github.head_ref }}"
